### PR TITLE
Fix for version glob error in #26

### PR DESCRIPTION
**Pull request by fatso83**
Fix for error in #26

The files section included `[^test}`, which will avoid including any file that has either `t`, `e`, `s`, or `t` in it. AFAIK the patterns section doesn't really employ true regexes, but glob patterns, which includes another way of specifying inverse matches.
.

[Validation](https://github.com/sinonjs/nise/pull/26#issuecomment-361186770)

### CODE REVIEW

**Comment by fatso83** [comment]
Whoops, don't merge. I reviewed my validation. Hold your horses, I'll update.

**Comment by fatso83** [comment]
This turned out to be more complex than I thought, due to various bugs and weird stuff in NPM. From the ["Files and Ignores"](https://github.com/npm/npm/wiki/Files-and-Ignores#files) section:
> "The consequences are undefined" if you try to negate any of the files entries (that is, "!foo.js"). Please don't. Use .npmignore.

Then there is the fact that NPM doesn't respect `.npmignore`, which is bug https://github.com/npm/npm/pull/11669 :hankey: 

There's a [workaround](https://github.com/npm/npm/pull/11669#issuecomment-315924254), though:
> Also: .npmignore/.gitignore in subdirectories DO override the top level files.

**Comment by f-roland** [comment]
@fatso83 any ETA on the resolution for this ? 
It fails production builds for us - as a dirty work around I need to explicitly add `nise@1.2.0` in my package.json file. Which is bad cause I'm pulling this from sinon.

**Comment by webdevian** [comment]
Explicitly adding nise@1.2.0 doesn't even seem to work in Yarn

**Comment by f-roland** [comment]
@webdevian maybe you need to clean your lock file so it removes any reference of nise@1.2.1 ? 
did the trick for me through `npm uninstall nise && npm install nise@1.2.0 --save`

**Comment by fatso83** [comment]
This is now correct, as the output from tar doesn't contain any test references `(rm -r package; npm pack 2>/dev/null && tar tzf nise-1.2.1.tgz 2>/dev/null) 2>/dev/null | grep test `

**Comment by webdevian** [comment]
Yeah I tried that, it adds an entry for both 1.2.0 and ^1.2.0 which resolves to 1.2.1. I feel like this is a probably a flaw in yarn

**Comment by Flarna** [comment]
Maybe the latest tag should be moved also to 1.2.0.

**Comment by f-roland** [comment]
@fatso83 I see the deprecation message, but the issue is still there... can't you just unpublish this version until it is fixed ?
It will fail all builds using sinon, and other libraries that pull this package with a carret-ed version...

**Comment by webdevian** [comment]
The fix in Yarn (v1) is to use a resolution
``` json
"resolutions": {
  "nise": "1.2.0"
},
```

**Comment by fatso83** [comment]
Version 1.2.2 was released some minutes ago and version 1.2.1 has been retracted, as per @f-roland's suggestion:

```
npm i nise@1.2.1
npm ERR! code ETARGET
npm ERR! notarget No matching version found for nise@1.2.1
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

I was under the impression that NPM  couldn't unpublish after the `leftpad` incident, and thought the deprecation thing would do more or less the same thing.

**Comment by f-roland** [comment]
Well luckily, unpublish still works :)
I don’t know what your release cycle is, but you could avoid this by publishing pre-release versions first, as those would be skipped by most user until you can make sure it’s iron-clad. 

This is especially important when you are required by big libraries like sinon that are very widely used !

**Comment by fatso83** [comment]
@f-roland Not sure if that would be avoiding anything, as very few people actively seek out pre-releases of libraries.

I would rather have someone suggest a good postbuild step for our CI server that validated the built package. #helpwanted

**Pull request merged**
