### PR TITLE
Use @sinonjs/text-encoding

### PR DESCRIPTION
**Pull request by fatso83**
This uses our new internal project 'text-encoding', which is
simply forked from the old (now deprecated) repo.

### CODE REVIEW

**Comment by mantoni** [comment]
From checking the `package-lock.json`, it seems like the new dependency was added, but the old `text-encoding` is still in the tree.

**Comment by mantoni** [comment]
Haha. Seems like we're both trigger happy today @fatso83 🔫

**Comment by fatso83** [comment]
@mantoni Doesn't matter though? The old one is a dependency of `sinon`, which depends on `nise (in an older version). As long as _this_ one still does not depend on `sinon` as an actual (non dev) dependency, that is.

**Comment by fatso83** [comment]
Maybe a hint we should have a `sinon-core` project - without the `lolex` and `nise` dependencies? Dunno.

**Comment by mantoni** [comment]
@fatso83 Aaah, good old circular dependencies 👍

**Comment by mantoni** [comment]
Re `sinon-core`, there was the idea once to entirely modularize sinon, like have spies, stubs and fakes live in a separate space and then let `sinon` just be the glue to have everything in one project. I'm not a friend of `core` things, but maybe `sinon-fakes`?

**Comment by fatso83** [comment]
It was well spotted though ... I forgot to update the actual references insie of the code, so running the tests gave me false positives. Fixed now.

**Comment by mroderick** [comment]
> Re `sinon-core`, there was the idea once to entirely modularize sinon, like have spies, stubs and fakes live in a separate space and then let `sinon` just be the glue to have everything in one project. I'm not a friend of `core` things, but maybe `sinon-fakes`?

I like the idea of `sinon-fakes`, but I also don't want to end up in the situation that Buster had, where they had a LOT of different modules to keep track of.

**Comment by mantoni** [comment]
> I also don't want to end up in the situation that Buster had

I agree. We shouldn't make things too atomic. I'm wondering if `sinon-fakes` could become all of `sinon` minus `nise` and `lolex`? Then `sinon` would "just" wire those 3 modules.

**Pull request merged**
