### PR TITLE
Add currentTarget to event

### PR DESCRIPTION
**Pull request by Omar2002**
This solve the problem with xhr requests in https://github.com/video-dev/hls.js

### CODE REVIEW

**Comment by mroderick** [comment]
> This solve the problem with xhr requests in https://github.com/video-dev/hls.js

Can you describe the problem in greater detail?

Please provide a test case that fails without your solution.

**Comment by fatso83** [comment]
@Omar2002 Nothing in that project description tells us what the problem is.

**Comment by Omar2002** [comment]
Sorry, for long time response.

This is a place in hls.js https://github.com/video-dev/hls.js/blob/8c706b9967902a632747ee0c88e2ac60279c1a6c/src/utils/xhr-loader.js#L84

**Comment by mad-gooze** [comment]
Hi @fatso83 @mroderick 
We use sinon and nise to automate tests for network requests in video player which uses hls.js library. The problem that @Omar2002 fixes here is that hls.js uses `currentTarget` event property in event listeners (https://github.com/video-dev/hls.js/blob/8c706b9967902a632747ee0c88e2ac60279c1a6c/src/utils/xhr-loader.js#L84) and this code breaks if we mock XHR via nise.

The `currentTime` property is defined by spec (https://dom.spec.whatwg.org/#dom-event-currenttarget) so I do not think there is no any problem in adding this property to Event class.

**Comment by mroderick** [comment]
@mad-gooze thank you for the update!

This PR still needs at least one test before we can merge it

**Comment by mad-gooze** [comment]
Is is ok to duplicate `event.target` checks for `event.currentTarget` in [fake-xhr/index.test.js](https://github.com/sinonjs/nise/blob/master/lib/fake-xhr/index.test.js) for tests?

**Comment by mroderick** [comment]
> Is is ok to duplicate event.target checks for event.currentTarget in fake-xhr/index.test.js for tests?

I think it's a good start. We can add another commit, if it turns out it's easy to extract for clarity

**Comment by Omar2002** [comment]
I added tests for currentTarget

**Comment by Omar2002** [comment]
Ping

**Comment by mroderick** [comment]
This has been published to npm as part of `nise@1.2.3`

**Pull request merged**
